name: dubster

services:
  client:
    build:
      context: "./client"
      target: "runner"
    ports:
      - "3000:3000"
    networks:
      - "private"

  # server:
  #   networks:
  #     - "private"

networks:
  private: {}
